# Generated by Django 5.0.3 on 2024-04-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_bal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='sex',
            field=models.CharField(choices=[('P', 'Other'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('P', 'Other'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='month',
            field=models.CharField(choices=[('Feb', 'February'), ('Mar', 'March'), ('Sep', 'September'), ('Nov', 'November'), ('Aug', 'August'), ('Dec', 'December'), ('Apr', 'April'), ('Jul', 'July'), ('May', 'May'), ('Oct', 'October'), ('Jan', 'January'), ('Jun', 'June')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('P', 'Other'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
