# Generated by Django 5.0.4 on 2024-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_bal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='sex',
            field=models.CharField(choices=[('P', 'Personnalisé'), ('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('P', 'Personnalisé'), ('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
    ]
