# Generated by Django 5.0.3 on 2024-04-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_bal', '0002_alter_coach_sex_alter_customer_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(choices=[('P', 'Premium'), ('S', 'Standard')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='month',
            field=models.CharField(choices=[('May', 'May'), ('Nov', 'November'), ('Apr', 'April'), ('Sep', 'September'), ('Jun', 'June'), ('Oct', 'October'), ('Mar', 'March'), ('Jul', 'July'), ('Dec', 'December'), ('Feb', 'February'), ('Jan', 'January'), ('Aug', 'August')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Other')], max_length=1),
        ),
    ]
