# Generated by Django 5.0.4 on 2024-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0.0)),
                ('age', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coachs')),
            ],
        ),
    ]
